# Generated by Django 5.2.5 on 2026-01-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_amount_paid_sale_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('PAY_NOW', 'Pay Now'), ('CREDIT', 'Credit')], default='PAY_NOW', max_length=20),
        ),
    ]
